### ISSUE TITLE
fail to make

### ISSUE THREAD

**Issue by junhag2** [lljbash/FastTT#1]
Hi,

I tried to build the FastTT code, but it fails to do so.
The following is the code  when make:

g++ -std=c++17 -Wall -Wextra -Wfloat-conversion -O3 -DNDEBUG -funroll-loops -march=native -Xpreprocessor -fopenmp   -c -MMD -MP -o sptensor2tt.o sptensor2tt.cc
sptensor2tt.cc: In function ‘void xerus::ttrounding(xerus::TTTensor&, size_t, int, double)’:
sptensor2tt.cc:249:105: error: invalid operands of types ‘void’ and ‘double’ to binary ‘operator/’
  249 |         double svdeps = calculate_svd(U, S, Vt, a.component(i), 2, max_rank, max_rank == 0 ? delta : 0) / norm_a;
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~
      |                                      |                                                                    |
      |                                      void                                                                 double
sptensor2tt.cc:276:105: error: invalid operands of types ‘void’ and ‘double’ to binary ‘operator/’
  276 |         double svdeps = calculate_svd(U, S, Vt, a.component(i), 1, max_rank, max_rank == 0 ? delta : 0) / norm_a;
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~
      |                                      |                                                                    |
      |                                      void                                                                 double
make: *** [<builtin>: sptensor2tt.o] Error 1

I have followed the guide for installing lapacke, lapack, blas,cblas, gfortran, suitesparse, boost, xerus. 
Can you take a look into this?

Thank you
Best,
Junhao

**Comment by lljbash** [comment]
Please follow the instruction of using the default FastTT-paper-version branch from my forked repo of xerus, where the return type of `calculate_svd` is `value_t`.

**Comment by junhag2** [comment]
Thank you for the fast response.
With the forked repo of xerus, this issue is addressed. but another one shows up:
LAPTOP-GMGEO7H9:~/FastTT$ make
g++ -std=c++17 -Wall -Wextra -Wfloat-conversion -O3 -DNDEBUG -funroll-loops -march=native -Xpreprocessor -fopenmp   -c -MMD -MP -o test.o test.cc
test.cc: In lambda function:
test.cc:78:25: error: ‘OptionParseException’ in namespace ‘cxxopts’ does not name a type
   78 |         catch (cxxopts::OptionParseException &) {
      |                         ^~~~~~~~~~~~~~~~~~~~
test.cc: In function ‘int main(int, char**)’:
test.cc:179:29: warning: loop variable ‘e’ creates a copy from type ‘const std::pair<long unsigned int, long unsigned int>’ [-Wrange-loop-construct]
  179 |             for (const auto e : edges) {
      |                             ^
test.cc:179:29: note: use reference type to prevent copying
  179 |             for (const auto e : edges) {
      |                             ^
      |                             &
make: *** [<builtin>: test.o] Error 1

In the test.cc file, i directly entered the path of the cxxopts.hpp file.

Thanks
Best,
Junhao

**Comment by lljbash** [comment]
Looks like the latest version of cxxopts has changed the name of its exception classes. Simply using `catch (...)` will definitely fix this.

**Comment by junhag2** [comment]
do you mind explaining a little more? How and where should I add the catch (...) in what files?

**Comment by lljbash** [comment]
Replace this part,
> test.cc: In lambda function:
> test.cc:78:25: error: ‘OptionParseException’ in namespace ‘cxxopts’ does not name a type
> 78 | catch (cxxopts::OptionParseException &) {

I am not going to teach you about C++ syntax, pls refer to https://en.cppreference.com/w/cpp/language/try_catch.

btw, you could try harder to understand the messages from the compiler, and then you will be able to solve this sort of problems by yourself easily.

**Comment by junhag2** [comment]
Thank you. It works now.
I am very new to C++, and not quite sure whether there will be other downstream effect.

**Comment by lljbash** [comment]
> Thank you. It works now. I am very new to C++, and not quite sure whether there will be other downstream effect.

Good luck with your research then.
